// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZJ52JyrJ9J_BkR7sYC5-AxrvqdezHMfI',
    appId: '1:639576600772:android:3464a2014f5eb0af031991',
    messagingSenderId: '639576600772',
    projectId: 'habitriseapp',
    storageBucket: 'habitriseapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKMTGL-_Nn4jBks6vY4KwMrtqK9TNGK0',
    appId: '1:639576600772:ios:7c58b8594127f12c031991',
    messagingSenderId: '639576600772',
    projectId: 'habitriseapp',
    storageBucket: 'habitriseapp.firebasestorage.app',
    iosClientId: '639576600772-756spufiegn8pg83mjokb32kt5b92tlj.apps.googleusercontent.com',
    iosBundleId: 'com.appsweat.habitrise',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5hj7cFvn5XOqjz6xfozxtWYkDyYjRtg',
    appId: '1:639576600772:web:c899c846bb878140031991',
    messagingSenderId: '639576600772',
    projectId: 'habitriseapp',
    authDomain: 'habitriseapp.firebaseapp.com',
    storageBucket: 'habitriseapp.firebasestorage.app',
    measurementId: 'G-7P806ZDWW7',
  );

}